# Generated by Django 3.1.5 on 2021-01-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.CharField(max_length=100)),
                ('practice_id', models.CharField(max_length=100)),
                ('book_number', models.CharField(max_length=30)),
                ('practice_type', models.CharField(max_length=100)),
                ('practice_description', models.CharField(max_length=100)),
                ('registration_record_number', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_licence_number', models.CharField(blank=True, max_length=100, null=True)),
                ('economic_record_number', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('medicine_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('medicine_activity_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data rozpoczęcia działalności')),
                ('medicine_activity_start_date_article_104', models.DateTimeField(blank=True, null=True, verbose_name='Data rozpoczęcia działalności art. 104')),
                ('medicine_activity_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia działalności')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
