# Generated by Django 3.1.5 on 2021-01-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20210106_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.CharField(blank=True, max_length=100, null=True)),
                ('book_number', models.CharField(blank=True, max_length=100, null=True)),
                ('practice_type', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_id', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_institution_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('regon', models.CharField(blank=True, max_length=100, null=True)),
                ('address_type', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_documentation_address_when_call', models.CharField(blank=True, max_length=1000, null=True)),
                ('practice_code', models.CharField(blank=True, max_length=100, null=True)),
                ('practice_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('teryt', models.CharField(blank=True, max_length=100, null=True)),
                ('teryt_description', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=1000, null=True)),
                ('street_number', models.CharField(blank=True, max_length=100, null=True)),
                ('local_number', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('post_office', models.CharField(blank=True, max_length=100, null=True)),
                ('simc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('street_code', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
